---
title: "Machine Learning Ensemble Model"
output: github_document
---
 
```{r}
#Loading the required libraries
library('caret')

#Setting the random seed
set.seed(1)

#Loading the dataset
data<-read.csv('C:/Users/Pavan/Desktop/Ensemble.csv')

#Structure of dataset
str(data)
```

```{r}
#Missing values
sum(is.na(data))

#Imputing missing values using median
preProcValues <- preProcess(data, method = c("medianImpute","center","scale"))

library('RANN')
data_processed <- predict(preProcValues, data)

sum(is.na(data_processed))
```

```{r}
#Spliting training set into two parts based on outcome: 75% and 25%
index <- createDataPartition(data_processed$Loan_Status, p=0.75, list=FALSE)
trainSet <- data_processed[ index,]
testSet <- data_processed[-index,]
```

```{r}
#Defining the training controls for multiple models
fitControl <- trainControl(
  method = "cv",
  number = 5,
  savePredictions = 'final',
  classProbs = T)

#Defining the predictors and outcome
predictors<-c("Credit_History", "LoanAmount", "Loan_Amount_Term", "ApplicantIncome",
              "CoapplicantIncome")
outcomeName<-'Loan_Status'
```

```{r}
#Training the random forest model
model_rf<-train(trainSet[,predictors],trainSet[,outcomeName],method='rf',trControl=fitControl,tuneLength=3)

#Predicting using random forest model
testSet$pred_rf<-predict(object = model_rf,testSet[,predictors])

#Checking the accuracy of the random forest model
confusionMatrix(testSet$Loan_Status,testSet$pred_rf)
```

```{r}
#Training the knn model
model_knn<-train(trainSet[,predictors],trainSet[,outcomeName],method='knn',trControl=fitControl,tuneLength=3)

#Predicting using knn model
testSet$pred_knn<-predict(object = model_knn,testSet[,predictors])

#Checking the accuracy of the knn model
confusionMatrix(testSet$Loan_Status,testSet$pred_knn)
```

```{r}
#Training the logistic regression model
model_lr<-train(trainSet[,predictors],trainSet[,outcomeName],method='glm',trControl=fitControl,tuneLength=3)

#Predicting using logistic regression model
testSet$pred_lr<-predict(object = model_lr,testSet[,predictors])

#Checking the accuracy of the logistic regression model
confusionMatrix(testSet$Loan_Status,testSet$pred_lr)
```

```{r}
## AVERAGING ##

#Predicting the probabilities
testSet$pred_rf_prob<-predict(object = model_rf,testSet[,predictors],type='prob')
testSet$pred_knn_prob<-predict(object = model_knn,testSet[,predictors],type='prob')
testSet$pred_lr_prob<-predict(object = model_lr,testSet[,predictors],type='prob')

#Taking average of predictions
testSet$pred_avg<-(testSet$pred_rf_prob$Y+testSet$pred_knn_prob$Y+testSet$pred_lr_prob$Y)/3

#Splitting into binary classes at 0.5
testSet$pred_avg<-as.factor(ifelse(testSet$pred_avg>0.5,'Y','N'))

#Checking the accuracy of average ensemble model
confusionMatrix(testSet$Loan_Status,testSet$pred_avg)
```

```{r}
## MAJORITY VOTING ##

#The majority vote
testSet$pred_majority<-as.factor(ifelse(testSet$pred_rf=='Y' & testSet$pred_knn=='Y','Y',ifelse(testSet$pred_rf=='Y' & testSet$pred_lr=='Y','Y',ifelse(testSet$pred_knn=='Y' & testSet$pred_lr=='Y','Y','N'))))

#Checking the accuracy of majority voting ensemble model
confusionMatrix(testSet$Loan_Status,testSet$pred_majority)
```

```{r}
## WEIGHTED AVERAGE ##

#Taking weighted average of predictions
testSet$pred_weighted_avg<-(testSet$pred_rf_prob$Y*0.25)+(testSet$pred_knn_prob$Y*0.25)+(testSet$pred_lr_prob$Y*0.5)

#Splitting into binary classes at 0.5
testSet$pred_weighted_avg<-as.factor(ifelse(testSet$pred_weighted_avg>0.5,'Y','N'))

#Checking the accuracy of weighted average ensemble model
confusionMatrix(testSet$Loan_Status,testSet$pred_weighted_avg)
```

```{r}
## Predict using each base layer model for training data and test data ##

#Predicting the out of fold prediction probabilities for training data
trainSet$OOF_pred_rf<-model_rf$pred$Y[order(model_rf$pred$rowIndex)]
trainSet$OOF_pred_knn<-model_knn$pred$Y[order(model_knn$pred$rowIndex)]
trainSet$OOF_pred_lr<-model_lr$pred$Y[order(model_lr$pred$rowIndex)]

#Predicting probabilities for the test data
testSet$OOF_pred_rf<-predict(model_rf,testSet[predictors],type='prob')$Y
testSet$OOF_pred_knn<-predict(model_knn,testSet[predictors],type='prob')$Y
testSet$OOF_pred_lr<-predict(model_lr,testSet[predictors],type='prob')$Y
```

```{r}
## Train the top layer model on the predictions of the bottom layer models ##

#Predictors for top layer models 
predictors_top<-c('OOF_pred_rf','OOF_pred_knn','OOF_pred_lr')

#GBM as top layer model 
model_gbm<-train(trainSet[,predictors_top],trainSet[,outcomeName],method='gbm',trControl=fitControl,tuneLength=3)

#Logistic regression as top layer model
model_glm<-train(trainSet[,predictors_top],trainSet[,outcomeName],method='glm',trControl=fitControl,tuneLength=3)
```

```{r}
## Predict using the top layer model with the predictions of bottom layer models ##

#predict using GBM top layer model
testSet$gbm_stacked<-predict(model_gbm,testSet[,predictors_top])

#Check the accuracy of ensemble model with GBM as top layer
confusionMatrix(testSet$Loan_Status,testSet$gbm_stacked)
```

```{r}
#predict using logictic regression top layer model
testSet$glm_stacked<-predict(model_glm,testSet[,predictors_top])

#Check the accuracy of ensemble model with logistic regression as top layer
confusionMatrix(testSet$Loan_Status,testSet$glm_stacked)
```
